#!/bin/bash

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Backup hosts file
cp /etc/hosts /etc/hosts.bak

# Overwrite required entries
sed -i 's/^127.0.0.1\s\+localhost/127.0.0.2 localhost/' /etc/hosts

# Add or replace facebook.com resolution
grep -q "facebook.com" /etc/hosts
if [ $? -eq 0 ]; then
    sed -i 's/.*facebook.com/8.8.8.8 facebook.com/' /etc/hosts
else
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
